use crate::battle::{move_data::*, side_timer::*, *};

pub struct BattleState {
    type_flags: u32,
    terrain: u8,
    active_battler: u8,
    controller_exec_flags: u32,
    battlers_count: u8,
    battler_party_indexes: [u8; MAX_BATTLERS_COUNT],
    battler_positions: [u8; MAX_BATTLERS_COUNT],
    actions_by_turn_order: [u8; MAX_BATTLERS_COUNT],
    battler_by_turn_order: [u8; MAX_BATTLERS_COUNT],
    current_turn_action_number: u8,
    current_action_func_id: u8,
    // battle_mons: [BattleRkmn; MAX_BATTLERS_COUNT],
    current_move_pos: u8,
    chosen_move_pos: u8,
    current_move: u16,
    chosen_move: u16,
    called_move: u16,
    move_damage: i32,
    hp_dealt: i32,
    bide_damage: [i32; MAX_BATTLERS_COUNT],
    last_used_item: u16,
    last_used_ability: u8,
    battler_attacker: u8,
    battler_target: u8,
    battler_fainted: u8,
    effect_battler: u8,
    potential_item_effect_battler: u8,
    absent_battler_flags: u8,
    crit_multiplier: u8,
    multi_hit_counter: u8,
    chosen_action_by_battler: [u8; MAX_BATTLERS_COUNT],
    last_printed_moves: BattlerMoves,
    last_moves: BattlerMoves,
    last_landed_moves: BattlerMoves,
    last_hit_by_type: BattlerMoves,
    last_resulting_moves: BattlerMoves,
    locked_moves: BattlerMoves,
    last_hit_by: [u8; MAX_BATTLERS_COUNT],
    chosen_move_by_battler: BattlerMoves,
    move_result_flags: u8,
    hit_marker: u32,
    bide_target: [u8; MAX_BATTLERS_COUNT],
    side_statuses: [u16; NUM_BATTLE_SIDES],
    side_timers: [SideTimer; NUM_BATTLE_SIDES],
    statuses_3: [u32; MAX_BATTLERS_COUNT],
    disable_structs: [DisableStruct; MAX_BATTLERS_COUNT],
    pause_counter_battle: u16,
    payday_money: u16,
    random_turn_number: u16,
    battle_outcome: u8,
    protect_structs: [ProtectStruct; MAX_BATTLERS_COUNT],
    // special_statuses: [SpecialStatus; MAX_BATTLERS_COUNT],
    battler_weather: u16,
    // wish_future_knock: WishFutureKnock,
    sent_mons_to_opponent: [u8; 2],
    dynamic_base_power: u16,
    exp_share_exp: u16,
    // battle_enigma_berries: [BattleEnigmaBerry; MAX_BATTLERS_COUNT],
    battle_struct: Battle,
    battle_resources: BattleResources,
    action_selection_cursor: [u8; MAX_BATTLERS_COUNT],
    move_selection_cursor: [u8; MAX_BATTLERS_COUNT],
    battler_status_summary_task_id: [u8; MAX_BATTLERS_COUNT],
    battler_in_menu_id: u8,
    doing_battle_anim: bool,
    transformed_personalities: [u32; MAX_BATTLERS_COUNT],
    player_dpad_hold_frames: u8,
    // battle_controller_opponent_healthbox_data: BattleHealthboxInfo,
    // battle_controller_opponent_flank_healthbox_data: BattleHealthboxInfo,
    battle_move_power: u16,
    move_to_learn: u16,
    battle_mon_forms: [u8; MAX_BATTLERS_COUNT],
}
