use super::Item;

pub enum CollectibleItem {
    None,
    Potion,
    Antidote,
    BurnHeal,
    IceHeal,
    Awakening,
    ParalyzeHeal,
    FullRestore,
    MaxPotion,
    HyperPotion,
    SuperPotion,
    FullHeal,
    Revive,
    MaxRevive,
    FreshWater,
    SodaPop,
    Lemonade,
    MooMooMilk,
    EnergyPowder,
    EnergyRoot,
    HealPowder,
    RevivalHerb,
    Ether,
    MaxEther,
    Elixir,
    MaxElixir,
    LavaCookie,
    BlueFlute,
    YellowFlute,
    RedFlute,
    BlackFlute,
    WhiteFlute,
    BerryJuice,
    SacredAsh,
    ShoalSalt,
    ShoalShell,
    RedShard,
    BlueShard,
    YellowShard,
    GreenShard,
    HPUp,
    Protein,
    Iron,
    Carbos,
    Calcium,
    RareCandy,
    PPUp,
    Zinc,
    PPMax,
    GuardSpec,
    DireHit,
    XAttack,
    XDefend,
    XSpeed,
    XAccuracy,
    XSpecial,
    PokeDoll,
    FluffyTail,
    SuperRepel,
    MaxRepel,
    EscapeRope,
    Repel,
    SunStone,
    MoonStone,
    FireStone,
    ThunderStone,
    WaterStone,
    LeafStone,
    TinyMushroom,
    BigMushroom,
    Pearl,
    BigPearl,
    Stardust,
    StarPiece,
    Nugget,
    HeartScale,
    BrightPowder,
    WhiteHerb,
    MachoBrace,
    ExpShare,
    QuickClaw,
    SootheBell,
    MentalHerb,
    ChoiceBand,
    KingsRock,
    SilverPowder,
    AmuletCoin,
    CleanseTag,
    SoulDew,
    DeepSeaTooth,
    DeepSeaScale,
    SmokeBall,
    Everstone,
    FocusBand,
    LuckyEgg,
    ScopeLens,
    MetalCoat,
    Leftovers,
    DragonScale,
    LightBall,
    SoftSand,
    HardStone,
    MiracleSeed,
    BlackGlasses,
    BlackBelt,
    Magnet,
    MysticWater,
    SharpBeak,
    PoisonBarb,
    NeverMeltIce,
    SpellTag,
    TwistedSpoon,
    Charcoal,
    DragonFang,
    SilkScarf,
    UpGrade,
    ShellBell,
    SeaIncense,
    LaxIncense,
    LuckyPunch,
    MetalPowder,
    ThickClub,
    Stick,
    RedScarf,
    BlueScarf,
    PinkScarf,
    GreenScarf,
    YellowScarf,
}

impl Item for CollectibleItem {
    fn name(&self) -> &str {
        match self {
            CollectibleItem::None => "None",
            CollectibleItem::Potion => "Potion",
            CollectibleItem::Antidote => "Antidote",
            CollectibleItem::BurnHeal => "Burn Heal",
            CollectibleItem::IceHeal => "Ice Heal",
            CollectibleItem::Awakening => "Awakening",
            CollectibleItem::ParalyzeHeal => "Paralyze Heal",
            CollectibleItem::FullRestore => "Full Restore",
            CollectibleItem::MaxPotion => "Max Potion",
            CollectibleItem::HyperPotion => "Hyper Potion",
            CollectibleItem::SuperPotion => "Super Potion",
            CollectibleItem::FullHeal => "Full Heal",
            CollectibleItem::Revive => "Revive",
            CollectibleItem::MaxRevive => "Max Revive",
            CollectibleItem::FreshWater => "Fresh Water",
            CollectibleItem::SodaPop => "Soda Pop",
            CollectibleItem::Lemonade => "Lemonade",
            CollectibleItem::MooMooMilk => "MooMoo Milk",
            CollectibleItem::EnergyPowder => "Energy Powder",
            CollectibleItem::EnergyRoot => "Energy Root",
            CollectibleItem::HealPowder => "Heal Powder",
            CollectibleItem::RevivalHerb => "Revival Herb",
            CollectibleItem::Ether => "Ether",
            CollectibleItem::MaxEther => "Max Ether",
            CollectibleItem::Elixir => "Elixir",
            CollectibleItem::MaxElixir => "Max Elixir",
            CollectibleItem::LavaCookie => "Lava Cookie",
            CollectibleItem::BlueFlute => "Blue Flute",
            CollectibleItem::YellowFlute => "Yellow Flute",
            CollectibleItem::RedFlute => "Red Flute",
            CollectibleItem::BlackFlute => "Black Flute",
            CollectibleItem::WhiteFlute => "White Flute",
            CollectibleItem::BerryJuice => "Berry Juice",
            CollectibleItem::SacredAsh => "Sacred Ash",
            CollectibleItem::ShoalSalt => "Shoal Salt",
            CollectibleItem::ShoalShell => "Shoal Shell",
            CollectibleItem::RedShard => "Red Shard",
            CollectibleItem::BlueShard => "Blue Shard",
            CollectibleItem::YellowShard => "Yellow Shard",
            CollectibleItem::GreenShard => "Green Shard",
            CollectibleItem::HPUp => "HP Up",
            CollectibleItem::Protein => "Protein",
            CollectibleItem::Iron => "Iron",
            CollectibleItem::Carbos => "Carbos",
            CollectibleItem::Calcium => "Calcium",
            CollectibleItem::RareCandy => "Rare Candy",
            CollectibleItem::PPUp => "PP Up",
            CollectibleItem::Zinc => "Zinc",
            CollectibleItem::PPMax => "PP Max",
            CollectibleItem::GuardSpec => "Guard Spec",
            CollectibleItem::DireHit => "Dire Hit",
            CollectibleItem::XAttack => "X Attack",
            CollectibleItem::XDefend => "X Defend",
            CollectibleItem::XSpeed => "X Speed",
            CollectibleItem::XAccuracy => "X Accuracy",
            CollectibleItem::XSpecial => "X Special",
            CollectibleItem::PokeDoll => "Poke Doll",
            CollectibleItem::FluffyTail => "Fluffy Tail",
            CollectibleItem::SuperRepel => "Super Repel",
            CollectibleItem::MaxRepel => "Max Repel",
            CollectibleItem::EscapeRope => "Escape Rope",
            CollectibleItem::Repel => "Repel",
            CollectibleItem::SunStone => "Sun Stone",
            CollectibleItem::MoonStone => "Moon Stone",
            CollectibleItem::FireStone => "Fire Stone",
            CollectibleItem::ThunderStone => "Thunder Stone",
            CollectibleItem::WaterStone => "Water Stone",
            CollectibleItem::LeafStone => "Leaf Stone",
            CollectibleItem::TinyMushroom => "Tiny Mushroom",
            CollectibleItem::BigMushroom => "Big Mushroom",
            CollectibleItem::Pearl => "Pearl",
            CollectibleItem::BigPearl => "Big Pearl",
            CollectibleItem::Stardust => "Stardust",
            CollectibleItem::StarPiece => "Star Piece",
            CollectibleItem::Nugget => "Nugget",
            CollectibleItem::HeartScale => "Heart Scale",
            CollectibleItem::BrightPowder => "Bright Powder",
            CollectibleItem::WhiteHerb => "White Herb",
            CollectibleItem::MachoBrace => "Macho Brace",
            CollectibleItem::ExpShare => "Exp Share",
            CollectibleItem::QuickClaw => "Quick Claw",
            CollectibleItem::SootheBell => "Soothe Bell",
            CollectibleItem::MentalHerb => "Mental Herb",
            CollectibleItem::ChoiceBand => "Choice Band",
            CollectibleItem::KingsRock => "Kings Rock",
            CollectibleItem::SilverPowder => "Silver Powder",
            CollectibleItem::AmuletCoin => "Amulet Coin",
            CollectibleItem::CleanseTag => "Cleanse Tag",
            CollectibleItem::SoulDew => "Soul Dew",
            CollectibleItem::DeepSeaTooth => "Deep Sea Tooth",
            CollectibleItem::DeepSeaScale => "Deep Sea Scale",
            CollectibleItem::SmokeBall => "Smoke Ball",
            CollectibleItem::Everstone => "Everstone",
            CollectibleItem::FocusBand => "Focus Band",
            CollectibleItem::LuckyEgg => "Lucky Egg",
            CollectibleItem::ScopeLens => "Scope Lens",
            CollectibleItem::MetalCoat => "Metal Coat",
            CollectibleItem::Leftovers => "Leftovers",
            CollectibleItem::DragonScale => "Dragon Scale",
            CollectibleItem::LightBall => "Light Ball",
            CollectibleItem::SoftSand => "Soft Sand",
            CollectibleItem::HardStone => "Hard Stone",
            CollectibleItem::MiracleSeed => "Miracle Seed",
            CollectibleItem::BlackGlasses => "Black Glasses",
            CollectibleItem::BlackBelt => "Black Belt",
            CollectibleItem::Magnet => "Magnet",
            CollectibleItem::MysticWater => "Mystic Water",
            CollectibleItem::SharpBeak => "Sharp Beak",
            CollectibleItem::PoisonBarb => "Poison Barb",
            CollectibleItem::NeverMeltIce => "Never Melt Ice",
            CollectibleItem::SpellTag => "Spell Tag",
            CollectibleItem::TwistedSpoon => "Twisted Spoon",
            CollectibleItem::Charcoal => "Charcoal",
            CollectibleItem::DragonFang => "Dragon Fang",
            CollectibleItem::SilkScarf => "Silk Scarf",
            CollectibleItem::UpGrade => "Up Grade",
            CollectibleItem::ShellBell => "Shell Bell",
            CollectibleItem::SeaIncense => "Sea Incense",
            CollectibleItem::LaxIncense => "Lax Incense",
            CollectibleItem::LuckyPunch => "Lucky Punch",
            CollectibleItem::MetalPowder => "Metal Powder",
            CollectibleItem::ThickClub => "Thick Club",
            CollectibleItem::Stick => "Stick",
            CollectibleItem::RedScarf => "Red Scarf",
            CollectibleItem::BlueScarf => "Blue Scarf",
            CollectibleItem::PinkScarf => "Pink Scarf",
            CollectibleItem::GreenScarf => "Green Scarf",
            CollectibleItem::YellowScarf => "Yellow Scarf",
        }
    }

    fn description(&self) -> &str {
        // TODO: Implement descriptions
        self.name()
    }

    fn value(&self) -> u16 {
        // TODO: Implement values
        16
    }
}
